jobs:
  include:
    - stage: build and test
      language: java
      jdk: openjdk8
      script: ./gradlew license buildPlugin
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
